using System.ComponentModel;
using System.Runtime.CompilerServices;
using Microsoft.Maui.Controls.Xaml;

namespace ZoneGuide.Mobile.Localization;

public sealed class AppLocalizer : INotifyPropertyChanged
{
    public static AppLocalizer Instance { get; } = new();

    private readonly Dictionary<string, Dictionary<string, string>> _translations =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["vi-VN"] = BuildVietnamese(),
            ["en-US"] = BuildEnglish(),
            ["zh-CN"] = BuildChinese(),
            ["ja-JP"] = BuildJapanese(),
            ["ko-KR"] = BuildKorean(),
            ["fr-FR"] = BuildFrench()
        };

    private string _language = "vi-VN";

    public event PropertyChangedEventHandler? PropertyChanged;

    public string CurrentLanguage => _language;

    public string this[string key] => Translate(key);

    public void SetLanguage(string? languageCode)
    {
        var normalized = NormalizeLanguage(languageCode);
        if (string.Equals(_language, normalized, StringComparison.OrdinalIgnoreCase))
            return;

        _language = normalized;
        OnPropertyChanged(null);
    }

    public string Translate(string key, string? fallback = null)
    {
        if (_translations.TryGetValue(_language, out var languageMap) &&
            languageMap.TryGetValue(key, out var translated))
        {
            return translated;
        }

        if (_translations.TryGetValue("en-US", out var englishMap) &&
            englishMap.TryGetValue(key, out translated))
        {
            return translated;
        }

        return fallback ?? key;
    }

    public string TranslateCategory(string? category)
    {
        if (string.IsNullOrWhiteSpace(category))
            return Translate("category_shopping");

        return category.Trim().ToLowerInvariant() switch
        {
            "hải sản & ốc" or "hai san & oc" or "seafood & snails" or "seafood" => Translate("category_tourism"),
            "ăn vặt" or "an vat" or "snacks" or "snack" => Translate("category_service"),
            "lẩu & nướng" or "lau & nuong" or "hotpot & grill" or "hotpot" or "grill" => Translate("category_food"),
            "nhậu" or "nhau" or "drinking" or "pub" => Translate("category_entertainment"),
            "giải khát" or "giai khat" or "beverage" or "beverages" or "drinks" => Translate("category_drinks"),
            "ăn no" or "an no" or "hearty meals" or "main meal" => Translate("category_shopping"),

            // Backward compatibility for old category names
            "du lịch" or "tourism" => Translate("category_tourism"),
            "dịch vụ" or "service" or "services" => Translate("category_service"),
            "ăn uống" or "food" or "food & drink" => Translate("category_food"),
            "giải trí" or "entertainment" => Translate("category_entertainment"),
            "mua sắm" or "shopping" or "khác" or "other" => Translate("category_shopping"),
            _ => category
        };
    }

    public string TranslateLanguageName(string? languageCode)
    {
        return languageCode?.ToLowerInvariant() switch
        {
            "vi-vn" => Translate("language_vietnamese"),
            "en-us" => Translate("language_english"),
            "zh-cn" => Translate("language_chinese"),
            "ja-jp" => Translate("language_japanese"),
            "ko-kr" => Translate("language_korean"),
            "fr-fr" => Translate("language_french"),
            _ => languageCode ?? Translate("language_vietnamese")
        };
    }

    private static string NormalizeLanguage(string? languageCode)
    {
        if (string.IsNullOrWhiteSpace(languageCode))
            return "vi-VN";

        languageCode = languageCode.Trim();
        if (languageCode.StartsWith("vi", StringComparison.OrdinalIgnoreCase))
            return "vi-VN";
        if (languageCode.StartsWith("en", StringComparison.OrdinalIgnoreCase))
            return "en-US";
        if (languageCode.StartsWith("zh", StringComparison.OrdinalIgnoreCase))
            return "zh-CN";
        if (languageCode.StartsWith("ja", StringComparison.OrdinalIgnoreCase))
            return "ja-JP";
        if (languageCode.StartsWith("ko", StringComparison.OrdinalIgnoreCase))
            return "ko-KR";
        if (languageCode.StartsWith("fr", StringComparison.OrdinalIgnoreCase))
            return "fr-FR";

        return "en-US";
    }

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    private static Dictionary<string, string> BuildVietnamese() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["tab_pois"] = "Địa điểm",
        ["tab_map"] = "Bản đồ",
        ["tab_history"] = "Lịch sử",
        ["tab_offline"] = "Offline",
        ["tab_tours"] = "Tour",
        ["tab_settings"] = "Cài đặt",
        ["offline_title"] = "Offline",
        ["offline_subtitle"] = "Quản lý audio pack nghe offline",
        ["offline_download_all"] = "↓ Tải tất cả",
        ["offline_clear_all"] = "Xóa hết",
        ["offline_filter_all"] = "Tất cả",
        ["offline_filter_downloaded"] = "Đã tải",
        ["offline_filter_pending"] = "Chưa tải",
        ["offline_empty_title"] = "Chưa có audio pack phù hợp",
        ["offline_empty_subtitle"] = "Hãy đổi bộ lọc hoặc tải nội dung để nghe không cần mạng.",
        ["offline_track_list"] = "Danh sách track",
        ["offline_audio_unit"] = "audio",
        ["offline_downloaded_at"] = "Da tai {0}",
        ["offline_delete_title"] = "Xóa gói offline",
        ["offline_delete_message"] = "Bạn có muốn xóa '{0}' khỏi thiết bị không?",
        ["offline_download_done_title"] = "Hoàn tất",
        ["offline_download_done_message"] = "Đã tải '{0}' để nghe offline.",
        ["offline_download_all_done_message"] = "Các audio pack đã sẵn sàng để nghe offline.",
        ["offline_clear_all_title"] = "Xóa tất cả",
        ["offline_clear_all_message"] = "Bạn có muốn xóa toàn bộ audio pack đã tải không?",
        ["offline_clear_all_done_message"] = "Đã xóa toàn bộ audio pack offline.",
        ["pois_title"] = "Địa điểm",
        ["pois_search_placeholder"] = "Tìm kiếm địa điểm...",
        ["pois_filter_title"] = "Lọc",
        ["pois_filter_all"] = "Tất cả",
        ["pois_count_suffix"] = "địa điểm tham quan",
        ["pois_empty_title"] = "Không có địa điểm phù hợp",
        ["pois_empty_subtitle"] = "Thử đổi từ khóa tìm kiếm hoặc bộ lọc danh mục.",
        ["poi_detail_title"] = "Chi tiết địa điểm",
        ["poi_detail_listen"] = "Thuyết minh",
        ["poi_detail_description"] = "Mô tả chi tiết",
        ["poi_detail_navigate"] = "Chỉ đường",
        ["poi_detail_share"] = "Chia sẻ",
        ["poi_detail_back"] = "Quay lại",
        ["poi_detail_stop"] = "Dừng",
        ["poi_detail_now_playing"] = "Đang phát",
        ["poi_detail_ready"] = "Sẵn sàng phát",
        ["poi_detail_tts"] = "Đang đọc bằng TTS",
        ["history_title"] = "Lịch sử",
        ["history_subtitle"] = "Các địa điểm bạn đã nghe thuyết minh",
        ["history_empty_title"] = "Không có lịch sử nghe",
        ["history_empty_subtitle"] = "Khi bạn phát một địa điểm, lịch sử sẽ xuất hiện ở đây.",
        ["history_delete"] = "Xóa",
        ["history_replay"] = "Nghe lại",
        ["map_title"] = "Bản đồ",
        ["map_search_placeholder"] = "Tìm kiếm địa điểm...",
        ["map_priority"] = "Ưu tiên",
        ["tours_title"] = "Tour",
        ["tours_empty_title"] = "Chưa có tour nào",
        ["tour_detail_points"] = "Điểm dừng",
        ["tour_detail_duration"] = "Thời lượng",
        ["tour_detail_distance"] = "Khoảng cách",
        ["tour_detail_start"] = "Bắt đầu tour",
        ["tour_detail_offline"] = "Ngoại tuyến",
        ["tour_detail_stops"] = "Các điểm nổi bật",
        ["tour_detail_about"] = "Giới thiệu tour",
        ["tour_detail_pois"] = "Các điểm trong tour",
        ["tour_detail_offline_ready"] = "Đã lưu trên thiết bị và sẵn sàng khi không có mạng",
        ["tour_detail_offline_prompt"] = "Tải hình ảnh và nội dung tour để dùng khi kết nối yếu",
        ["tour_detail_download_offline"] = "Tải xuống",
        ["tour_detail_remove_offline"] = "Gỡ xuống",
        ["tour_detail_downloading"] = "Đang tải nội dung để sử dụng ngoại tuyến",
        ["tour_detail_downloading_short"] = "Đang tải",
        ["tour_detail_highlights_empty"] = "Khám phá lộ trình để xem các điểm dừng nổi bật.",
        ["tour_detail_download_success_title"] = "Thành công",
        ["tour_detail_download_success_message"] = "Đã tải nội dung offline thành công",
        ["tour_detail_download_error_title"] = "Lỗi",
        ["tour_detail_download_error_message"] = "Không thể tải nội dung offline",
        ["tour_detail_delete_confirm_title"] = "Xác nhận",
        ["tour_detail_delete_confirm_message"] = "Bạn có muốn xóa nội dung offline của tour này không?",
        ["settings_title"] = "Cài đặt",
        ["settings_audio"] = "Âm thanh",
        ["settings_language"] = "Ngôn ngữ",
        ["settings_voice"] = "Giọng đọc",
        ["settings_test_voice"] = "Test giọng đọc",
        ["settings_save"] = "Lưu cài đặt",
        ["settings_sync"] = "Đồng bộ",
        ["settings_sync_button"] = "Đồng bộ dữ liệu",
        ["settings_upload_analytics"] = "Tải lên dữ liệu phân tích",
        ["settings_speed"] = "Tốc độ đọc",
        ["settings_volume"] = "Âm lượng",
        ["settings_gps"] = "GPS và vị trí",
        ["settings_gps_accuracy"] = "Độ chính xác GPS",
        ["settings_gps_low"] = "Thấp (tiết kiệm pin)",
        ["settings_gps_medium"] = "Trung bình",
        ["settings_gps_high"] = "Cao (chính xác nhất)",
        ["settings_trigger_radius"] = "Bán kính kích hoạt",
        ["settings_approach_radius"] = "Bán kính cảnh báo",
        ["settings_cooldown"] = "Thời gian chờ",
        ["settings_behavior"] = "Hành vi",
        ["settings_auto_play"] = "Tự động phát khi vào vùng",
        ["settings_notify_approach"] = "Thông báo khi đến gần",
        ["settings_background_tracking"] = "Theo dõi ở nền",
        ["settings_battery_saver"] = "Chế độ tiết kiệm pin",
        ["settings_offline_mode"] = "Chế độ Offline",
        ["settings_last_sync"] = "Lần cuối",
        ["settings_other"] = "Khác",
        ["settings_logout_user"] = "Đăng xuất user",
        ["settings_clear_cache"] = "Xóa cache",
        ["settings_save_success_title"] = "Thành công",
        ["settings_save_success_message"] = "Đã lưu cài đặt",
        ["settings_sync_success_message"] = "Đã đồng bộ dữ liệu",
        ["settings_sync_error_title"] = "Lỗi",
        ["settings_sync_error_message"] = "Không thể đồng bộ dữ liệu",
        ["settings_upload_success_message"] = "Đã tải lên dữ liệu phân tích",
        ["settings_upload_error_message"] = "Không thể tải lên dữ liệu",
        ["tracking_start"] = "Bắt đầu theo dõi",
        ["tracking_stop"] = "Dừng theo dõi",
        ["sync_in_progress"] = "Đang đồng bộ...",
        ["settings_clear_cache_confirm_title"] = "Xác nhận",
        ["settings_clear_cache_confirm_message"] = "Bạn có chắc muốn xóa tất cả dữ liệu cache?",
        ["settings_clear_cache_success_message"] = "Đã xóa cache",
        ["settings_logout_confirm_title"] = "Đăng xuất",
        ["settings_logout_confirm_message"] = "Bạn có chắc muốn đăng xuất khỏi ứng dụng?",
        ["login_title"] = "Đăng nhập",
        ["login_subtitle"] = "Vui lòng đăng nhập để sử dụng ZoneGuide",
        ["login_email"] = "Email",
        ["login_password"] = "Mật khẩu",
        ["login_password_placeholder"] = "Nhập mật khẩu",
        ["login_button"] = "Đăng nhập",
        ["login_required"] = "Vui lòng nhập email và mật khẩu",
        ["login_failed"] = "Đăng nhập thất bại",
        ["login_error_prefix"] = "Lỗi đăng nhập",
        ["history_places_count"] = "địa điểm",
        ["history_delete_confirm"] = "Xóa mục lịch sử của '{0}'?",
        ["duration_hour_short"] = "h",
        ["duration_minute_short"] = "ph",
        ["duration_minute"] = "phút",
        ["duration_second_short"] = "s",
        ["language_vietnamese"] = "Tiếng Việt",
        ["language_english"] = "English",
        ["language_chinese"] = "中文",
        ["language_japanese"] = "日本語",
        ["language_korean"] = "한국어",
        ["language_french"] = "Français",
    ["category_tourism"] = "Hải sản & ốc",
    ["category_service"] = "Ăn vặt",
    ["category_food"] = "Lẩu & nướng",
    ["category_entertainment"] = "Nhậu",
    ["category_drinks"] = "Giải khát",
    ["category_shopping"] = "Ăn no",
    ["category_other"] = "Ăn no",
        ["status_just_now"] = "Vừa xong",
        ["status_minutes_ago"] = "phút trước",
        ["status_hours_ago"] = "giờ trước",
        ["status_yesterday"] = "Hôm qua",
        ["status_today"] = "Hôm nay",
        ["status_not_found"] = "Không tìm thấy",
        ["alert_ok"] = "OK",
        ["alert_cancel"] = "Hủy",
        ["alert_delete"] = "Xóa"
    };

    private static Dictionary<string, string> BuildEnglish() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["tab_pois"] = "Places",
        ["tab_map"] = "Map",
        ["tab_history"] = "History",
        ["tab_offline"] = "Offline",
        ["tab_tours"] = "Tours",
        ["tab_settings"] = "Settings",
        ["offline_title"] = "Offline",
        ["offline_subtitle"] = "Manage audio packs for offline listening",
        ["offline_download_all"] = "↓ Download all",
        ["offline_clear_all"] = "Clear all",
        ["offline_filter_all"] = "All",
        ["offline_filter_downloaded"] = "Downloaded",
        ["offline_filter_pending"] = "Not downloaded",
        ["offline_empty_title"] = "No offline packs found",
        ["offline_empty_subtitle"] = "Try another filter or download content for offline listening.",
        ["offline_track_list"] = "Track list",
        ["offline_audio_unit"] = "audio",
        ["offline_downloaded_at"] = "Downloaded {0}",
        ["offline_delete_title"] = "Delete offline pack",
        ["offline_delete_message"] = "Do you want to remove '{0}' from this device?",
        ["offline_download_done_title"] = "Done",
        ["offline_download_done_message"] = "Downloaded '{0}' for offline use.",
        ["offline_download_all_done_message"] = "Offline packs are ready.",
        ["offline_clear_all_title"] = "Clear all",
        ["offline_clear_all_message"] = "Do you want to remove all downloaded offline packs?",
        ["offline_clear_all_done_message"] = "All offline packs have been removed.",
        ["pois_title"] = "Places",
        ["pois_search_placeholder"] = "Search places...",
        ["pois_filter_title"] = "Filter",
        ["pois_filter_all"] = "All",
        ["pois_count_suffix"] = "places to visit",
        ["pois_empty_title"] = "No matching places",
        ["pois_empty_subtitle"] = "Try another keyword or category filter.",
        ["poi_detail_title"] = "Place details",
        ["poi_detail_listen"] = "Narration",
        ["poi_detail_description"] = "Detailed description",
        ["poi_detail_navigate"] = "Navigate",
        ["poi_detail_share"] = "Share",
        ["poi_detail_back"] = "Back",
        ["poi_detail_stop"] = "Stop",
        ["poi_detail_now_playing"] = "Now playing",
        ["poi_detail_ready"] = "Ready to play",
        ["poi_detail_tts"] = "Playing with TTS",
        ["history_title"] = "History",
        ["history_subtitle"] = "Places you have listened to",
        ["history_empty_title"] = "No listening history",
        ["history_empty_subtitle"] = "Once you play a place, its history will appear here.",
        ["history_delete"] = "Delete",
        ["history_replay"] = "Replay",
        ["map_title"] = "Map",
        ["map_search_placeholder"] = "Search places...",
        ["map_priority"] = "Priority",
        ["tours_title"] = "Tours",
        ["tours_empty_title"] = "No tours yet",
        ["tour_detail_points"] = "Stops",
        ["tour_detail_duration"] = "Duration",
        ["tour_detail_distance"] = "Distance",
        ["tour_detail_start"] = "Start tour",
        ["tour_detail_offline"] = "Offline",
        ["tour_detail_stops"] = "Highlights",
        ["tour_detail_about"] = "About this tour",
        ["tour_detail_pois"] = "Points of interest",
        ["tour_detail_offline_ready"] = "Saved on this device and ready without internet",
        ["tour_detail_offline_prompt"] = "Download images and tour content for limited connectivity",
        ["tour_detail_download_offline"] = "Download",
        ["tour_detail_remove_offline"] = "Remove",
        ["tour_detail_downloading"] = "Downloading content for offline use",
        ["tour_detail_downloading_short"] = "Downloading",
        ["tour_detail_highlights_empty"] = "Explore the route to discover featured stops.",
        ["tour_detail_download_success_title"] = "Success",
        ["tour_detail_download_success_message"] = "Offline content downloaded successfully",
        ["tour_detail_download_error_title"] = "Error",
        ["tour_detail_download_error_message"] = "Unable to download offline content",
        ["tour_detail_delete_confirm_title"] = "Confirm",
        ["tour_detail_delete_confirm_message"] = "Do you want to remove offline content for this tour?",
        ["settings_title"] = "Settings",
        ["settings_audio"] = "Audio",
        ["settings_language"] = "Language",
        ["settings_voice"] = "Voice",
        ["settings_test_voice"] = "Test voice",
        ["settings_save"] = "Save settings",
        ["settings_sync"] = "Sync",
        ["settings_sync_button"] = "Sync data",
        ["settings_upload_analytics"] = "Upload analytics",
        ["settings_speed"] = "Reading speed",
        ["settings_volume"] = "Volume",
        ["settings_gps"] = "GPS and location",
        ["settings_gps_accuracy"] = "GPS accuracy",
        ["settings_gps_low"] = "Low (battery saver)",
        ["settings_gps_medium"] = "Medium",
        ["settings_gps_high"] = "High (most accurate)",
        ["settings_trigger_radius"] = "Trigger radius",
        ["settings_approach_radius"] = "Approach radius",
        ["settings_cooldown"] = "Cooldown",
        ["settings_behavior"] = "Behavior",
        ["settings_auto_play"] = "Autoplay when entering range",
        ["settings_notify_approach"] = "Notify on approach",
        ["settings_background_tracking"] = "Background tracking",
        ["settings_battery_saver"] = "Battery saver mode",
        ["settings_offline_mode"] = "Offline mode",
        ["settings_last_sync"] = "Last sync",
        ["settings_other"] = "Other",
        ["settings_logout_user"] = "Sign out user",
        ["settings_clear_cache"] = "Clear cache",
        ["settings_save_success_title"] = "Success",
        ["settings_save_success_message"] = "Settings saved",
        ["settings_sync_success_message"] = "Data synced successfully",
        ["settings_sync_error_title"] = "Error",
        ["settings_sync_error_message"] = "Unable to sync data",
        ["settings_upload_success_message"] = "Analytics uploaded",
        ["settings_upload_error_message"] = "Unable to upload analytics",
        ["tracking_start"] = "Start tracking",
        ["tracking_stop"] = "Stop tracking",
        ["sync_in_progress"] = "Syncing...",
        ["settings_clear_cache_confirm_title"] = "Confirm",
        ["settings_clear_cache_confirm_message"] = "Do you want to clear all cached data?",
        ["settings_clear_cache_success_message"] = "Cache cleared",
        ["settings_logout_confirm_title"] = "Sign out",
        ["settings_logout_confirm_message"] = "Do you want to sign out of the app?",
        ["login_title"] = "Sign in",
        ["login_subtitle"] = "Please sign in to continue with ZoneGuide",
        ["login_email"] = "Email",
        ["login_password"] = "Password",
        ["login_password_placeholder"] = "Enter your password",
        ["login_button"] = "Sign in",
        ["login_required"] = "Please enter email and password",
        ["login_failed"] = "Sign in failed",
        ["login_error_prefix"] = "Sign in error",
        ["history_places_count"] = "places",
        ["history_delete_confirm"] = "Delete history item '{0}'?",
        ["duration_hour_short"] = "h",
        ["duration_minute_short"] = "m",
        ["duration_minute"] = "minutes",
        ["duration_second_short"] = "s",
        ["language_vietnamese"] = "Vietnamese",
        ["language_english"] = "English",
        ["language_chinese"] = "Chinese",
        ["language_japanese"] = "Japanese",
        ["language_korean"] = "Korean",
        ["language_french"] = "French",
    ["category_tourism"] = "Seafood & snails",
    ["category_service"] = "Snacks",
    ["category_food"] = "Hotpot & grill",
    ["category_entertainment"] = "Drinking",
    ["category_drinks"] = "Beverages",
    ["category_shopping"] = "Hearty meals",
    ["category_other"] = "Hearty meals",
        ["status_just_now"] = "Just now",
        ["status_minutes_ago"] = "minutes ago",
        ["status_hours_ago"] = "hours ago",
        ["status_yesterday"] = "Yesterday",
        ["status_today"] = "Today",
        ["status_not_found"] = "Not found",
        ["alert_ok"] = "OK",
        ["alert_cancel"] = "Cancel",
        ["alert_delete"] = "Delete"
    };

    private static Dictionary<string, string> BuildChinese() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["tab_pois"] = "地点",
        ["tab_map"] = "地图",
        ["tab_history"] = "历史",
        ["tab_tours"] = "路线",
        ["tab_settings"] = "设置",
        ["pois_title"] = "地点",
        ["pois_search_placeholder"] = "搜索地点...",
        ["pois_filter_title"] = "筛选",
        ["pois_empty_title"] = "没有匹配的地点",
        ["pois_empty_subtitle"] = "请尝试其他关键词或分类。",
        ["poi_detail_title"] = "地点详情",
        ["poi_detail_listen"] = "语音讲解",
        ["poi_detail_description"] = "详细介绍",
        ["poi_detail_navigate"] = "导航",
        ["poi_detail_share"] = "分享",
        ["poi_detail_back"] = "返回",
        ["poi_detail_now_playing"] = "正在播放",
        ["poi_detail_ready"] = "准备播放",
        ["poi_detail_tts"] = "TTS 正在朗读",
        ["history_title"] = "历史",
        ["history_subtitle"] = "你已收听过的地点",
        ["history_empty_title"] = "暂无收听历史",
        ["history_empty_subtitle"] = "播放地点后，历史会显示在这里。",
        ["history_delete"] = "删除",
        ["history_replay"] = "重听",
        ["map_title"] = "地图",
        ["map_search_placeholder"] = "搜索地点...",
        ["map_priority"] = "优先级",
        ["tours_title"] = "路线",
        ["tours_empty_title"] = "暂无路线",
        ["tour_detail_points"] = "站点",
        ["tour_detail_duration"] = "时长",
        ["tour_detail_distance"] = "距离",
        ["tour_detail_start"] = "开始路线",
        ["tour_detail_offline"] = "离线",
        ["tour_detail_stops"] = "亮点",
        ["tour_detail_about"] = "路线介绍",
        ["tour_detail_pois"] = "兴趣点",
        ["tour_detail_offline_ready"] = "已保存到设备，可在无网络时使用",
        ["tour_detail_offline_prompt"] = "下载图片和路线内容，以便在弱网时使用",
        ["tour_detail_download_offline"] = "下载",
        ["tour_detail_remove_offline"] = "移除",
        ["tour_detail_downloading"] = "正在下载离线内容",
        ["tour_detail_downloading_short"] = "下载中",
        ["tour_detail_highlights_empty"] = "探索路线以发现精选站点。",
        ["tour_detail_download_success_title"] = "成功",
        ["tour_detail_download_success_message"] = "离线内容下载成功",
        ["tour_detail_download_error_title"] = "错误",
        ["tour_detail_download_error_message"] = "无法下载离线内容",
        ["tour_detail_delete_confirm_title"] = "确认",
        ["tour_detail_delete_confirm_message"] = "要移除此路线的离线内容吗？",
        ["settings_title"] = "设置",
        ["settings_audio"] = "音频",
        ["settings_language"] = "语言",
        ["settings_voice"] = "语音",
        ["settings_test_voice"] = "试听语音",
        ["settings_save"] = "保存设置",
        ["settings_sync"] = "同步",
        ["settings_sync_button"] = "同步数据",
        ["settings_upload_analytics"] = "上传分析数据",
        ["language_vietnamese"] = "越南语",
        ["language_english"] = "英语",
        ["language_chinese"] = "中文",
        ["language_japanese"] = "日语",
        ["language_korean"] = "韩语",
        ["language_french"] = "法语",
    ["category_tourism"] = "海鲜与螺类",
    ["category_service"] = "小吃",
    ["category_food"] = "火锅与烧烤",
    ["category_entertainment"] = "饮酒",
    ["category_drinks"] = "饮品",
    ["category_shopping"] = "饱腹正餐",
    ["category_other"] = "饱腹正餐"
    };

    private static Dictionary<string, string> BuildJapanese() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["tab_pois"] = "スポット",
        ["tab_map"] = "地図",
        ["tab_history"] = "履歴",
        ["tab_tours"] = "ツアー",
        ["tab_settings"] = "設定",
        ["pois_title"] = "スポット",
        ["pois_search_placeholder"] = "スポットを検索...",
        ["pois_filter_title"] = "絞り込み",
        ["pois_empty_title"] = "一致するスポットがありません",
        ["pois_empty_subtitle"] = "キーワードまたはカテゴリを変更してください。",
        ["poi_detail_title"] = "スポット詳細",
        ["poi_detail_listen"] = "音声ガイド",
        ["poi_detail_description"] = "詳細説明",
        ["poi_detail_navigate"] = "ナビ",
        ["poi_detail_share"] = "共有",
        ["poi_detail_back"] = "戻る",
        ["poi_detail_now_playing"] = "再生中",
        ["poi_detail_ready"] = "再生準備完了",
        ["poi_detail_tts"] = "TTS で再生中",
        ["history_title"] = "履歴",
        ["history_subtitle"] = "再生したスポット",
        ["history_empty_title"] = "再生履歴がありません",
        ["history_empty_subtitle"] = "スポットを再生するとここに表示されます。",
        ["history_delete"] = "削除",
        ["history_replay"] = "再生",
        ["map_title"] = "地図",
        ["map_search_placeholder"] = "スポットを検索...",
        ["map_priority"] = "優先度",
        ["tours_title"] = "ツアー",
        ["tours_empty_title"] = "ツアーはまだありません",
        ["tour_detail_points"] = "立ち寄り",
        ["tour_detail_duration"] = "所要時間",
        ["tour_detail_distance"] = "距離",
        ["tour_detail_start"] = "ツアー開始",
        ["tour_detail_offline"] = "オフライン",
        ["tour_detail_stops"] = "見どころ",
        ["tour_detail_about"] = "ツアー紹介",
        ["tour_detail_pois"] = "スポット一覧",
        ["tour_detail_offline_ready"] = "端末に保存済みで、オフラインでも利用できます",
        ["tour_detail_offline_prompt"] = "通信が不安定でも使えるよう画像とツアー内容を保存します",
        ["tour_detail_download_offline"] = "ダウンロード",
        ["tour_detail_remove_offline"] = "削除",
        ["tour_detail_downloading"] = "オフライン用コンテンツをダウンロード中",
        ["tour_detail_downloading_short"] = "ダウンロード中",
        ["tour_detail_highlights_empty"] = "ルートをたどって見どころを見つけましょう。",
        ["tour_detail_download_success_title"] = "完了",
        ["tour_detail_download_success_message"] = "オフラインコンテンツを保存しました",
        ["tour_detail_download_error_title"] = "エラー",
        ["tour_detail_download_error_message"] = "オフラインコンテンツをダウンロードできませんでした",
        ["tour_detail_delete_confirm_title"] = "確認",
        ["tour_detail_delete_confirm_message"] = "このツアーのオフラインコンテンツを削除しますか？",
        ["settings_title"] = "設定",
        ["settings_audio"] = "音声",
        ["settings_language"] = "言語",
        ["settings_voice"] = "音声",
        ["settings_test_voice"] = "音声テスト",
        ["settings_save"] = "設定を保存",
        ["settings_sync"] = "同期",
        ["settings_sync_button"] = "データ同期",
        ["settings_upload_analytics"] = "分析データを送信",
        ["language_vietnamese"] = "ベトナム語",
        ["language_english"] = "英語",
        ["language_chinese"] = "中国語",
        ["language_japanese"] = "日本語",
        ["language_korean"] = "韓国語",
        ["language_french"] = "フランス語",
    ["category_tourism"] = "海鮮・巻貝",
    ["category_service"] = "軽食",
    ["category_food"] = "鍋・焼き物",
    ["category_entertainment"] = "飲み",
    ["category_drinks"] = "ドリンク",
    ["category_shopping"] = "しっかりご飯",
    ["category_other"] = "しっかりご飯"
    };

    private static Dictionary<string, string> BuildKorean() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["tab_pois"] = "장소",
        ["tab_map"] = "지도",
        ["tab_history"] = "기록",
        ["tab_tours"] = "투어",
        ["tab_settings"] = "설정",
        ["pois_title"] = "장소",
        ["pois_search_placeholder"] = "장소 검색...",
        ["pois_filter_title"] = "필터",
        ["pois_empty_title"] = "일치하는 장소가 없습니다",
        ["pois_empty_subtitle"] = "다른 키워드나 카테고리를 시도해 보세요.",
        ["poi_detail_title"] = "장소 상세",
        ["poi_detail_listen"] = "오디오 가이드",
        ["poi_detail_description"] = "상세 설명",
        ["poi_detail_navigate"] = "길찾기",
        ["poi_detail_share"] = "공유",
        ["poi_detail_back"] = "뒤로",
        ["poi_detail_now_playing"] = "재생 중",
        ["poi_detail_ready"] = "재생 준비 완료",
        ["poi_detail_tts"] = "TTS 재생 중",
        ["history_title"] = "기록",
        ["history_subtitle"] = "재생한 장소",
        ["history_empty_title"] = "재생 기록이 없습니다",
        ["history_empty_subtitle"] = "장소를 재생하면 여기에 표시됩니다.",
        ["history_delete"] = "삭제",
        ["history_replay"] = "다시 듣기",
        ["map_title"] = "지도",
        ["map_search_placeholder"] = "장소 검색...",
        ["map_priority"] = "우선순위",
        ["tours_title"] = "투어",
        ["tours_empty_title"] = "투어가 없습니다",
        ["tour_detail_points"] = "정차 지점",
        ["tour_detail_duration"] = "소요 시간",
        ["tour_detail_distance"] = "거리",
        ["tour_detail_start"] = "투어 시작",
        ["tour_detail_offline"] = "오프라인",
        ["tour_detail_stops"] = "하이라이트",
        ["tour_detail_about"] = "투어 소개",
        ["tour_detail_pois"] = "관심 장소",
        ["tour_detail_offline_ready"] = "기기에 저장되어 인터넷 없이도 사용할 수 있습니다",
        ["tour_detail_offline_prompt"] = "연결이 약할 때를 대비해 이미지와 투어 내용을 다운로드하세요",
        ["tour_detail_download_offline"] = "다운로드",
        ["tour_detail_remove_offline"] = "삭제",
        ["tour_detail_downloading"] = "오프라인 콘텐츠를 다운로드하는 중입니다",
        ["tour_detail_downloading_short"] = "다운로드 중",
        ["tour_detail_highlights_empty"] = "경로를 탐색해 주요 정차 지점을 확인하세요.",
        ["tour_detail_download_success_title"] = "완료",
        ["tour_detail_download_success_message"] = "오프라인 콘텐츠를 다운로드했습니다",
        ["tour_detail_download_error_title"] = "오류",
        ["tour_detail_download_error_message"] = "오프라인 콘텐츠를 다운로드할 수 없습니다",
        ["tour_detail_delete_confirm_title"] = "확인",
        ["tour_detail_delete_confirm_message"] = "이 투어의 오프라인 콘텐츠를 삭제할까요?",
        ["settings_title"] = "설정",
        ["settings_audio"] = "오디오",
        ["settings_language"] = "언어",
        ["settings_voice"] = "음성",
        ["settings_test_voice"] = "음성 테스트",
        ["settings_save"] = "설정 저장",
        ["settings_sync"] = "동기화",
        ["settings_sync_button"] = "데이터 동기화",
        ["settings_upload_analytics"] = "분석 데이터 업로드",
        ["language_vietnamese"] = "베트남어",
        ["language_english"] = "영어",
        ["language_chinese"] = "중국어",
        ["language_japanese"] = "일본어",
        ["language_korean"] = "한국어",
        ["language_french"] = "프랑스어",
    ["category_tourism"] = "해산물 & 소라",
    ["category_service"] = "간식",
    ["category_food"] = "전골 & 구이",
    ["category_entertainment"] = "술자리",
    ["category_drinks"] = "음료",
    ["category_shopping"] = "든든한 식사",
    ["category_other"] = "든든한 식사"
    };

    private static Dictionary<string, string> BuildFrench() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["tab_pois"] = "Lieux",
        ["tab_map"] = "Carte",
        ["tab_history"] = "Historique",
        ["tab_tours"] = "Circuits",
        ["tab_settings"] = "Paramètres",
        ["pois_title"] = "Lieux",
        ["pois_search_placeholder"] = "Rechercher un lieu...",
        ["pois_filter_title"] = "Filtrer",
        ["pois_empty_title"] = "Aucun lieu correspondant",
        ["pois_empty_subtitle"] = "Essayez un autre mot-clé ou filtre.",
        ["poi_detail_title"] = "Détail du lieu",
        ["poi_detail_listen"] = "Narration",
        ["poi_detail_description"] = "Description détaillée",
        ["poi_detail_navigate"] = "Itinéraire",
        ["poi_detail_share"] = "Partager",
        ["poi_detail_back"] = "Retour",
        ["poi_detail_now_playing"] = "Lecture en cours",
        ["poi_detail_ready"] = "Prêt à lire",
        ["poi_detail_tts"] = "Lecture TTS",
        ["history_title"] = "Historique",
        ["history_subtitle"] = "Les lieux que vous avez écoutés",
        ["history_empty_title"] = "Aucun historique",
        ["history_empty_subtitle"] = "Lorsque vous lancez un lieu, il apparaîtra ici.",
        ["history_delete"] = "Supprimer",
        ["history_replay"] = "Réécouter",
        ["map_title"] = "Carte",
        ["map_search_placeholder"] = "Rechercher un lieu...",
        ["map_priority"] = "Priorité",
        ["tours_title"] = "Circuits",
        ["tours_empty_title"] = "Aucun circuit",
        ["tour_detail_points"] = "Étapes",
        ["tour_detail_duration"] = "Durée",
        ["tour_detail_distance"] = "Distance",
        ["tour_detail_start"] = "Commencer le circuit",
        ["tour_detail_offline"] = "Hors ligne",
        ["tour_detail_stops"] = "Points forts",
        ["tour_detail_about"] = "À propos du circuit",
        ["tour_detail_pois"] = "Points d'intérêt",
        ["tour_detail_offline_ready"] = "Enregistré sur cet appareil et prêt sans connexion",
        ["tour_detail_offline_prompt"] = "Téléchargez les images et le contenu pour une utilisation avec connexion limitée",
        ["tour_detail_download_offline"] = "Télécharger",
        ["tour_detail_remove_offline"] = "Retirer",
        ["tour_detail_downloading"] = "Téléchargement du contenu hors ligne",
        ["tour_detail_downloading_short"] = "Téléchargement",
        ["tour_detail_highlights_empty"] = "Explorez l’itinéraire pour découvrir les arrêts proposés.",
        ["tour_detail_download_success_title"] = "Succès",
        ["tour_detail_download_success_message"] = "Le contenu hors ligne a été téléchargé",
        ["tour_detail_download_error_title"] = "Erreur",
        ["tour_detail_download_error_message"] = "Impossible de télécharger le contenu hors ligne",
        ["tour_detail_delete_confirm_title"] = "Confirmer",
        ["tour_detail_delete_confirm_message"] = "Voulez-vous supprimer le contenu hors ligne de ce circuit ?",
        ["settings_title"] = "Paramètres",
        ["settings_audio"] = "Audio",
        ["settings_language"] = "Langue",
        ["settings_voice"] = "Voix",
        ["settings_test_voice"] = "Tester la voix",
        ["settings_save"] = "Enregistrer",
        ["settings_sync"] = "Synchronisation",
        ["settings_sync_button"] = "Synchroniser les données",
        ["settings_upload_analytics"] = "Envoyer les analyses",
        ["language_vietnamese"] = "Vietnamien",
        ["language_english"] = "Anglais",
        ["language_chinese"] = "Chinois",
        ["language_japanese"] = "Japonais",
        ["language_korean"] = "Coréen",
        ["language_french"] = "Français",
    ["category_tourism"] = "Fruits de mer & escargots",
    ["category_service"] = "Snacks",
    ["category_food"] = "Fondue & grillades",
    ["category_entertainment"] = "Apéro",
    ["category_drinks"] = "Boissons",
    ["category_shopping"] = "Repas copieux",
    ["category_other"] = "Repas copieux"
    };
}

[ContentProperty(nameof(Key))]
public class TranslateExtension : IMarkupExtension<BindingBase>
{
    public string Key { get; set; } = string.Empty;

    public BindingBase ProvideValue(IServiceProvider serviceProvider)
    {
        return new Binding($"[{Key}]", source: AppLocalizer.Instance);
    }

    object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
    {
        return ProvideValue(serviceProvider);
    }
}
